config/routes.rb
require 'soulheart/server'
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
Bikeindex::Application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth/applications'
    controllers authorizations: 'oauth/authorizations'
    controllers authorized_applications: 'oauth/authorized_applications'
  end

  get '/shop', to: redirect('https://bikeindex.myshopify.com'), as: :shop
  get '/store', to: redirect('https://bikeindex.myshopify.com'), as: :store
  get '/discuss', to: redirect('https://discuss.bikeindex.org'), as: :discuss
  get 'discourse_authentication', to: 'discourse_authentication#index'

  resources :organizations do
    member do
      get :embed
      get :embed_extended
      get :embed_create_success
    end
  end

  get '/', to: redirect(:root_url, subdomain: false), constraints: { subdomain: 'stolen' }
  root to: 'welcome#index'

  LandingPages::ORGANIZATIONS.each do |slug|
    get slug, to: 'landing_pages#show', organization_id: slug
  end

  %w(for_shops for_advocacy for_law_enforcement for_schools new_homepage).freeze.each do |page|
    get page, controller: 'landing_pages', action: page
  end

  %w(update_browser user_home choose_registration goodbye bike_creation_graph).freeze.each do |page|
    get page, controller: 'welcome', action: page
  end

  get 'update_browser', to: 'welcome#update_browser'
  get 'user_home', to: 'welcome#user_home'
  get 'choose_registration', to: 'welcome#choose_registration'
  get 'goodbye', to: 'welcome#goodbye'
  get 'bike_creation_graph', to: 'welcome#bike_creation_graph'

  resource :session, only: [:new, :create, :destroy]
  get 'logout', to: 'sessions#destroy'

  resources :payments
  resources :documentation, only: [:index] do
    collection do
      get :api_v1
      get :api_v2
      get :api_v3
      get :o2c
      get :authorize
    end
  end

  resources :ownerships, only: [:show]
  resources :memberships, only: [:update, :destroy]

  resources :stolen_notifications, only: [:create, :new]

  resources :feedbacks, only: [:index, :create]
  get 'vendor_signup', to: redirect('/organizations/new')
  get 'connect_lightspeed', to: 'organizations#connect_lightspeed'
  get 'help', to: 'feedbacks#index'
  get 'feedbacks/new', to: redirect('/help')
  %w(support contact contact_us).each { |p| get p, to: redirect('/help') }

  resources :users, only: [:new, :create, :show, :edit, :update] do
    collection do
      get 'confirm'
      get 'request_password_reset'
      post 'password_reset'
      get 'password_reset'
      get 'update_password'
    end
  end
  get :my_account, to: 'users#edit', as: :my_account
  get :accept_vendor_terms, to: 'users#accept_vendor_terms'
  get :accept_terms, to: 'users#accept_terms'
  resources :user_embeds, only: [:show]
  resources :user_emails, only: [:destroy] do
    member do
      post 'resend_confirmation'
      get 'confirm'
      post 'make_primary'
    end
  end
  resources :news, only: [:show, :index]
  resources :blogs, only: [:show, :index]
  get 'blog', to: redirect('/news')

  resources :public_images, only: [:create, :show, :edit, :update, :destroy] do
    collection do
      post :order
    end
    member { post :is_private }
  end

  resources :registrations, only: [:new, :create] do
    collection { get :embed }
  end

  resources :bikes do
    collection { get :scanned }
    member do
      get :spokecard
      get :scanned
      get :pdf
    end
    resource :recovery, only: [:edit, :update], controller: 'bikes/recovery'
  end

  resources :locks, except: [:show, :index]

  namespace :admin do
    root to: 'dashboard#index'
    resources :bikes do
      collection do
        get :duplicates
        put :ignore_duplicate_toggle
        get :missing_manufacturer
        post :update_manufacturers
        put :unrecover
      end
      member { get :get_destroy }
    end
    get 'invitations', to: 'dashboard#invitations'
    get 'maintenance', to: 'dashboard#maintenance'
    put 'update_tsv_blacklist', to: 'dashboard#update_tsv_blacklist'
    get 'tsvs', to: 'dashboard#tsvs'
    get 'bust_z_cache', to: 'dashboard#bust_z_cache'
    get 'destroy_example_bikes', to: 'dashboard#destroy_example_bikes'
    resources :memberships, :organization_invitations,
              :paints, :ads, :recovery_displays, :mail_snippets
    resources :organizations do
      resources :custom_layouts, only: [:index, :edit, :update], controller: 'organizations/custom_layouts'
    end
    get 'recover_organization', to: 'organizations#recover'
    get 'show_deleted_organizations', to: 'organizations#show_deleted'

    resources :flavor_texts, only: [:destroy, :create]
    resources :stolen_bikes do
      member { post :approve }
    end
    resources :customer_contacts, only: [:create]
    resources :recoveries do
      collection { post :approve }
    end
    resources :stolen_notifications do
      member { get :resend }
    end
    resources :graphs, only: [:index] do
      collection do
        get :tables
        get :bikes
        get :users
        get :stolen_locations
      end
    end
    resources :failed_bikes, only: [:index, :show]
    resources :feedbacks, only: [:index, :show] do
      collection { get :graphs }
    end
    resources :ownerships, only: [:edit, :update]
    resources :tweets
    get 'blog', to: redirect('/news')
    resources :news do
      collection do
        get :listicle_image_edit
      end
    end
    resources :ctypes, only: [:new, :create, :index, :edit, :update, :destroy] do
      collection { post :import }
    end
    resources :manufacturers do
      collection { post :import }
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end

  namespace :api, defaults: { format: 'json' } do
    get '/', to: redirect('/documentation')
    namespace :v1 do
      resources :bikes, only: [:index, :show, :create] do
        collection do
          get 'search_tags'
          get 'close_serials'
          get 'stolen_ids'
        end
      end
      resources :stolen_locking_response_suggestions, only: [:index]
      resources :cycle_types, only: [:index]
      resources :wheel_sizes, only: [:index]
      resources :component_types, only: [:index]
      resources :colors, only: [:index]
      resources :handlebar_types, only: [:index]
      resources :frame_materials, only: [:index]
      resources :manufacturers, only: [:index, :show]
      resources :notifications, only: [:create]
      resources :organizations, only: [:show]
      resources :users do
        collection do
          get 'current'
          post 'request_serial_update'
          post 'send_request'
        end
      end
      get 'not_found', to: 'api_v1#not_found'
      get '*a', to: 'api_v1#not_found'
    end
    mount Soulheart::Server, at: '/autocomplete'
  end
  mount API::Base => '/api'

  resources :stolen, only: [:index, :show] do
    collection do
      get 'current_tsv'
    end
  end

  resources :manufacturers, only: [:index] do
    collection { get 'tsv' }
  end
  get 'manufacturers_tsv', to: 'manufacturers#tsv'

  resources :organization_deals, only: [:create, :new]
  resource :integrations, only: [:create]
  get '/auth/:provider/callback', to: 'integrations#create'
  get '/auth/failure', to: 'integrations#integrations_controller_creation_error'

  %w(support_the_index support_the_bike_index protect_your_bike privacy terms
     serials about where vendor_terms resources image_resources
     how_not_to_buy_stolen dev_and_design lightspeed).freeze.each do |page|
    get page, controller: 'info', action: page
  end
  get 'lightspeed_integration', to: redirect('/lightspeed')

  %w(stolen_bikes roadmap security spokecard how_it_works).freeze.each { |p| get p, to: redirect('/resources') }

  # get 'sitemap.xml.gz' => redirect('https://files.bikeindex.org/sitemaps/sitemap_index.xml.gz')
  # Somehow the redirect drops the .gz extension, which ruins it so this redirect is handled by Cloudflare
  # get 'sitemaps/(*all)' => redirect('https://files.bikeindex.org/sitemaps/%{all}')

  get '/400', to: 'errors#bad_request', via: :all
  get '/401', to: 'errors#unauthorized', via: :all
  get '/404', to: 'errors#not_found', via: :all
  get '/422', to: 'errors#unprocessable_entity', via: :all
  get '/500', to: 'errors#server_error', via: :all

  mount Sidekiq::Web => '/sidekiq', constraints: AdminRestriction

  # No actions are defined here, this `resources` declaration
  # prepends a :organization_id/ to every nested URL.
  # Down here so that it doesn't override any other routes
  resources :organizations, only: [], path: 'o', module: 'organized' do
    get '/', to: 'bikes#index', as: :root
    get 'landing', to: 'manage#landing', as: :landing
    resources :bikes, only: [:index, :new, :show] do
      collection { get :recoveries }
    end
    # Below are admin controllers, inherit from Organized::AdminController not BaseController
    resources :manage, only: [:index, :update, :destroy] do
      collection do
        get :dev
        get :locations
      end
    end
    resources :users, except: [:show]
    resources :emails
  end

  get '*unmatched_route', to: 'errors#not_found' if Rails.env.production? # Handle 404s with lograge
end

app/controllers/admin/recoveries_controller.rb
class Admin::RecoveriesController < Admin::BaseController
  def index
    if params[:posted]
      @posted = true
      recoveries = StolenRecord.recovery_unposted.includes(:bike).order("date_recovered desc")
    elsif params[:all_recoveries]
      recoveries = StolenRecord.recovered.includes(:bike).order("date_recovered desc")
    else 
      recoveries = StolenRecord.displayable.includes(:bike).order("date_recovered desc")
    end
    page = params[:page] || 1
    per_page = params[:per_page] || 50
    @recoveries = recoveries.page(page).per(per_page)
  end

  def show
    redirect_to edit_admin_recovery_url
  end

  def edit
    @recovery = StolenRecord.unscoped.find(params[:id])
    @bike = @recovery.bike.decorate
  end

  def update
    @stolen_record = StolenRecord.unscoped.find(params[:id])
    if @stolen_record.update_attributes(permitted_parameters)
      flash[:success] = 'Recovery Saved!'
      redirect_to admin_recoveries_url
    else
      raise StandardError
      render action: :edit
    end
  end

  def approve
    if params[:multipost]
      enqueued = false
      if params[:recovery_selected].present?
        params[:recovery_selected].keys.each do |rid|
          recovery = StolenRecord.unscoped.find(rid)
          unless recovery.recovery_posted && recovery.can_share_recovery == false
            RecoveryNotifyWorker.perform_async(rid.to_i)
            enqueued = true
          end
        end
      end
      if enqueued
        flash[:success] = "Recovery notifications enqueued. Recoveries marked 'can share' haven't been posted, because they need your loving caress."
      else 
        flash[:error] = "No recoveries were selected (or only recoveries you need to caress were)"
      end
      redirect_to admin_recoveries_url
    else
      RecoveryNotifyWorker.perform_async(params[:id].to_i)
      flash[:success] = 'Recovery notification enqueued.'
      redirect_to admin_recoveries_url
    end
  end

  private

  def permitted_parameters
    params.require(:stolen_record).permit(StolenRecord.old_attr_accessible)
  end
end

app/controllers/bikes/recovery_controller.rb
module Bikes
  class RecoveryController < ApplicationController
    before_filter :find_bike
    before_filter :ensure_token_match!
    layout 'application_revised'

    def edit
      # redirect to bike show and set session - so the token isn't available to on page js
      # and so we can render show with a modal
      session[:recovery_link_token] = params[:token]
      redirect_to bike_path(@bike)
    end

    def update
      if @stolen_record.add_recovery_information(permitted_params)
        EmailRecoveredFromLinkWorker.perform_async(@stolen_record.id)
        flash[:success] = 'Bike marked recovered! Thank you!'
        redirect_to bike_path(@bike)
      else
        render :edit, bike_id: @bike.id, token: params[:token]
      end
    end

    private

    def permitted_params
      params.require(:stolen_record).permit(:date_recovered, :recovered_description,
                                            :index_helped_recovery, :can_share_recovery)
    end

    def find_bike
      @bike = Bike.unscoped.find(params[:bike_id])
    rescue ActiveRecord::StatementInvalid => e
      raise e.to_s =~ /PG..NumericValueOutOfRange/ ? ActiveRecord::RecordNotFound : e
    end

    def ensure_token_match!
      @stolen_record = StolenRecord.find_matching_token(bike_id: @bike && @bike.id,
                                                        recovery_link_token: params[:token])
      if @stolen_record.present?
        return true if @bike.stolen
        flash[:info] = 'Bike has already been marked recovered!'
      else
        flash[:error] = 'Incorrect Token, check your email again'
      end
      redirect_to bike_path(@bike) and return
    end
  end
end

app/views/admin/recoveries/edit.html.haml
%header.with-subtitle#admin-recoveries
  %h1
    Edit recovery for #{@bike.type}
  %p
    = link_to "Back to recoveries", admin_recoveries_url
%p
  = link_to "Edit bike", edit_admin_bike_path(@bike)
%ul.bike-boxes
  = render partial: "/bikes/bike", locals: {bike: @bike, target: "show" }
.dl-holder
  %dl.dl-horizontal
    = @bike.dl_list_item(@bike.created_at.strftime("%m-%d-%Y"), "Created")
    = @bike.dl_from_attribute("owner_email")
    = @bike.dl_list_item(@bike.owner.email, "Current Owner")
    = @bike.dl_from_attribute("cached_data")
    %dt
      Location
    %dd
      = @recovery.address
  .dl-holder
    %h2
      - if @recovery.recovery_display.present?
        = link_to "Recovery displayed", edit_admin_recovery_display_url(@recovery.recovery_display)
      - else
        = link_to 'Display recovery', new_admin_recovery_display_url(stolen_record_id: @recovery.id), class: 'button-blue padded'        
        - if @recovery.recovery_posted
          Recovery posted

        / - elsif @recovery.can_share_recovery == true
        /   = link_to 'Share recovery', approve_admin_recoveries_url(id: @recovery.id), method: :post, confirm: "Approval will\n\n- Send out a tweet\n- And post to facebook.\n- It can NOT be effectively reversed\n", class: 'button-blue padded'
        / - else
        /   = link_to 'Post recovery (no share)', approve_admin_recoveries_url(id: @recovery.id), method: :post, class: 'button-blue padded'

%hr
- url = {action: "update", controller: "recoveries"}
= form_for([:admin, @recovery], :url => url , html: { class: "form form-horizontal" }) do |f|
  - if @recovery.errors.any?
    #alert-block
      .alert.alert-error
        %h4
          Please fix the following 
          = pluralize(@recovery.errors.count, "error")
        %ul
          - @recovery.errors.full_messages.each do |msg|
            %li
              = msg
  .control-group
    = f.label :index_helped_recovery, class: "control-label"
    .controls
      = f.check_box :index_helped_recovery
  
  .control-group
    = f.label :can_share_recovery, class: "control-label"
    .controls
      = f.check_box :can_share_recovery

  .padded
    %p
      = @recovery.recovered_description
  / .control-group.recovery-input-field
  /   = f.label :recovery_share, "Story to share",   class: "control-label"
  /   .controls
  /     = f.text_area :recovery_share
  / / tweets - 140 chars, - 23 for URL
  / - tweet_length = 140 - 23
  / - if @bike.thumb_image.present?
  /   / Minus 23 if bike has an image
  /   - tweet_length = tweet_length - 23
  / .control-group#tweet-entry.recovery-input-field{ data: {length: tweet_length } }
  /   = f.label :recovery_tweet, class: "control-label"
  /   .controls
  /     = f.text_area :recovery_tweet
  /   %span#tweet-length
  /     = tweet_length


  / .actions
  /   .control-group
  /     = submit_tag "Update the recovery", class: "button-green"
  /     

app/views/admin/recoveries/index.html.haml
%header.with-subtitle#admin-recoveries
  %h1
    Recoveries
    - unless @all_recoveries
      that can be displayed
    
  / - if @posted
  /   = link_to 'Only unposted', admin_recoveries_url, class: "sharing-links"
  - if @all_recoveries
    = link_to 'Only displayable', admin_recoveries_url, class: "sharing-links"
  - else
    = link_to 'All recoveries', admin_recoveries_url(all_recoveries: true), class: "sharing-links"


%h4
  = StolenRecord.recovered.count
  recoveries
%h4
  = StolenRecord.recovery_unposted.count
  are waiting to be posted

.paginate-container
  = paginate @recoveries
%section.full-screen-table
  = form_tag approve_admin_recoveries_path, class: '', id: 'multi_check' do
    = hidden_field_tag :multipost, true
    / - unless @posted
    /   .clearfix#multiapprove_submit
    /     = submit_tag 'Post checked recoveries', class: 'button-blue pull-right'
    %table.table.table-striped.table-bordered
      %thead
        / - unless @posted
        /   %th
        /     %input#all_select{ type: 'checkbox' }
        %th.date-recovered-cell
          Date recovered
        %th.medium-screens
          Bike
        %th
          Recovery info
        %th.large-screens
          Location
        %th.sm-cell
          H<span class="sm-cell-hide">elped</span>
        %th.sm-cell
          S<span class="sm-cell-hide">hareable</span>
        %th.sm-cell
          D<span class="sm-cell-hide">isplay</span>


      %tbody
        - @recoveries.each do |recovery|
          %tr
            / - unless @posted
            /   %td.multipost_checkbox
            /     = check_box_tag "recovery_selected[#{recovery.id}]", recovery.id

            %td
              %a{href: edit_admin_recovery_url(recovery.id) }
                - if recovery.date_recovered.present?
                  - date = recovery.date_recovered
                - else
                  - date = recovery.created_at
                  Stolen on
                = l date, format: :dotted

            %td.medium-screens
              - if recovery.bike.present?
                .less-strong-hold
                  %span.less-strong-right
                    = link_to recovery.bike_id, edit_admin_bike_url(recovery.bike)
                  = recovery.bike.title_string
                  - if recovery.estimated_value.present?
                    %small.less-strong
                      $#{recovery.estimated_value}
                
            %td
              - if recovery.recovered_description.present?
                = recovery.recovered_description
              .large-screens.less-strong
                = recovery.theft_description.truncate(200) if recovery.theft_description.present?
            %td.large-screens
              - if recovery.address.present?
                = recovery.city
            %td.table-cell-check.sm-cell
              / Posted
              / = "&#x2713;".html_safe if recovery.recovery_posted
              = "&#x2713;".html_safe if recovery.index_helped_recovery
            %td.table-cell-check.sm-cell
              = "&#x2713;".html_safe if recovery.can_share_recovery
            %td.table-cell-check.sm-cell
              - if recovery.recovery_display.present?
                = link_to "&#x2713;".html_safe, edit_admin_recovery_display_url(recovery.recovery_display)
          
  .paginate-container
    = paginate @recoveries
:scss
  @media (max-width: 700px) {
    .full-screen-table {
      table {
        table-layout: fixed;
        .date-recovered-cell { width: 6em; }
        .sm-cell { width: 2em; }
        .sm-cell-hide { display: none; }
      }
    }
  }
:javascript
  $(document).ready(function() {$('.full-screen-table').parents('.receptacle').css('max-width', '100%');});