config/routes.rb
require 'soulheart/server'
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
Bikeindex::Application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth/applications'
    controllers authorizations: 'oauth/authorizations'
    controllers authorized_applications: 'oauth/authorized_applications'
  end

  get '/shop', to: redirect('https://bikeindex.myshopify.com'), as: :shop
  get '/store', to: redirect('https://bikeindex.myshopify.com'), as: :store
  get '/discuss', to: redirect('https://discuss.bikeindex.org'), as: :discuss
  get 'discourse_authentication', to: 'discourse_authentication#index'

  resources :organizations do
    member do
      get :embed
      get :embed_extended
      get :embed_create_success
    end
  end

  get '/', to: redirect(:root_url, subdomain: false), constraints: { subdomain: 'stolen' }
  root to: 'welcome#index'

  LandingPages::ORGANIZATIONS.each do |slug|
    get slug, to: 'landing_pages#show', organization_id: slug
  end

  %w(for_shops for_advocacy for_law_enforcement for_schools new_homepage).freeze.each do |page|
    get page, controller: 'landing_pages', action: page
  end

  %w(update_browser user_home choose_registration goodbye bike_creation_graph).freeze.each do |page|
    get page, controller: 'welcome', action: page
  end

  get 'update_browser', to: 'welcome#update_browser'
  get 'user_home', to: 'welcome#user_home'
  get 'choose_registration', to: 'welcome#choose_registration'
  get 'goodbye', to: 'welcome#goodbye'
  get 'bike_creation_graph', to: 'welcome#bike_creation_graph'

  resource :session, only: [:new, :create, :destroy]
  get 'logout', to: 'sessions#destroy'

  resources :payments
  resources :documentation, only: [:index] do
    collection do
      get :api_v1
      get :api_v2
      get :api_v3
      get :o2c
      get :authorize
    end
  end

  resources :ownerships, only: [:show]
  resources :memberships, only: [:update, :destroy]

  resources :stolen_notifications, only: [:create, :new]

  resources :feedbacks, only: [:index, :create]
  get 'vendor_signup', to: redirect('/organizations/new')
  get 'connect_lightspeed', to: 'organizations#connect_lightspeed'
  get 'help', to: 'feedbacks#index'
  get 'feedbacks/new', to: redirect('/help')
  %w(support contact contact_us).each { |p| get p, to: redirect('/help') }

  resources :users, only: [:new, :create, :show, :edit, :update] do
    collection do
      get 'confirm'
      get 'request_password_reset'
      post 'password_reset'
      get 'password_reset'
      get 'update_password'
    end
  end
  get :my_account, to: 'users#edit', as: :my_account
  get :accept_vendor_terms, to: 'users#accept_vendor_terms'
  get :accept_terms, to: 'users#accept_terms'
  resources :user_embeds, only: [:show]
  resources :user_emails, only: [:destroy] do
    member do
      post 'resend_confirmation'
      get 'confirm'
      post 'make_primary'
    end
  end
  resources :news, only: [:show, :index]
  resources :blogs, only: [:show, :index]
  get 'blog', to: redirect('/news')

  resources :public_images, only: [:create, :show, :edit, :update, :destroy] do
    collection do
      post :order
    end
    member { post :is_private }
  end

  resources :registrations, only: [:new, :create] do
    collection { get :embed }
  end

  resources :bikes do
    collection { get :scanned }
    member do
      get :spokecard
      get :scanned
      get :pdf
    end
    resource :recovery, only: [:edit, :update], controller: 'bikes/recovery'
  end

  resources :locks, except: [:show, :index]

  namespace :admin do
    root to: 'dashboard#index'
    resources :bikes do
      collection do
        get :duplicates
        put :ignore_duplicate_toggle
        get :missing_manufacturer
        post :update_manufacturers
        put :unrecover
      end
      member { get :get_destroy }
    end
    get 'invitations', to: 'dashboard#invitations'
    get 'maintenance', to: 'dashboard#maintenance'
    put 'update_tsv_blacklist', to: 'dashboard#update_tsv_blacklist'
    get 'tsvs', to: 'dashboard#tsvs'
    get 'bust_z_cache', to: 'dashboard#bust_z_cache'
    get 'destroy_example_bikes', to: 'dashboard#destroy_example_bikes'
    resources :memberships, :organization_invitations,
              :paints, :ads, :recovery_displays, :mail_snippets
    resources :organizations do
      resources :custom_layouts, only: [:index, :edit, :update], controller: 'organizations/custom_layouts'
    end
    get 'recover_organization', to: 'organizations#recover'
    get 'show_deleted_organizations', to: 'organizations#show_deleted'

    resources :flavor_texts, only: [:destroy, :create]
    resources :stolen_bikes do
      member { post :approve }
    end
    resources :customer_contacts, only: [:create]
    resources :recoveries do
      collection { post :approve }
    end
    resources :stolen_notifications do
      member { get :resend }
    end
    resources :graphs, only: [:index] do
      collection do
        get :tables
        get :bikes
        get :users
        get :stolen_locations
      end
    end
    resources :failed_bikes, only: [:index, :show]
    resources :feedbacks, only: [:index, :show] do
      collection { get :graphs }
    end
    resources :ownerships, only: [:edit, :update]
    resources :tweets
    get 'blog', to: redirect('/news')
    resources :news do
      collection do
        get :listicle_image_edit
      end
    end
    resources :ctypes, only: [:new, :create, :index, :edit, :update, :destroy] do
      collection { post :import }
    end
    resources :manufacturers do
      collection { post :import }
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end

  namespace :api, defaults: { format: 'json' } do
    get '/', to: redirect('/documentation')
    namespace :v1 do
      resources :bikes, only: [:index, :show, :create] do
        collection do
          get 'search_tags'
          get 'close_serials'
          get 'stolen_ids'
        end
      end
      resources :stolen_locking_response_suggestions, only: [:index]
      resources :cycle_types, only: [:index]
      resources :wheel_sizes, only: [:index]
      resources :component_types, only: [:index]
      resources :colors, only: [:index]
      resources :handlebar_types, only: [:index]
      resources :frame_materials, only: [:index]
      resources :manufacturers, only: [:index, :show]
      resources :notifications, only: [:create]
      resources :organizations, only: [:show]
      resources :users do
        collection do
          get 'current'
          post 'request_serial_update'
          post 'send_request'
        end
      end
      get 'not_found', to: 'api_v1#not_found'
      get '*a', to: 'api_v1#not_found'
    end
    mount Soulheart::Server, at: '/autocomplete'
  end
  mount API::Base => '/api'

  resources :stolen, only: [:index, :show] do
    collection do
      get 'current_tsv'
    end
  end

  resources :manufacturers, only: [:index] do
    collection { get 'tsv' }
  end
  get 'manufacturers_tsv', to: 'manufacturers#tsv'

  resources :organization_deals, only: [:create, :new]
  resource :integrations, only: [:create]
  get '/auth/:provider/callback', to: 'integrations#create'
  get '/auth/failure', to: 'integrations#integrations_controller_creation_error'

  %w(support_the_index support_the_bike_index protect_your_bike privacy terms
     serials about where vendor_terms resources image_resources
     how_not_to_buy_stolen dev_and_design lightspeed).freeze.each do |page|
    get page, controller: 'info', action: page
  end
  get 'lightspeed_integration', to: redirect('/lightspeed')

  %w(stolen_bikes roadmap security spokecard how_it_works).freeze.each { |p| get p, to: redirect('/resources') }

  # get 'sitemap.xml.gz' => redirect('https://files.bikeindex.org/sitemaps/sitemap_index.xml.gz')
  # Somehow the redirect drops the .gz extension, which ruins it so this redirect is handled by Cloudflare
  # get 'sitemaps/(*all)' => redirect('https://files.bikeindex.org/sitemaps/%{all}')

  get '/400', to: 'errors#bad_request', via: :all
  get '/401', to: 'errors#unauthorized', via: :all
  get '/404', to: 'errors#not_found', via: :all
  get '/422', to: 'errors#unprocessable_entity', via: :all
  get '/500', to: 'errors#server_error', via: :all

  mount Sidekiq::Web => '/sidekiq', constraints: AdminRestriction

  # No actions are defined here, this `resources` declaration
  # prepends a :organization_id/ to every nested URL.
  # Down here so that it doesn't override any other routes
  resources :organizations, only: [], path: 'o', module: 'organized' do
    get '/', to: 'bikes#index', as: :root
    get 'landing', to: 'manage#landing', as: :landing
    resources :bikes, only: [:index, :new, :show] do
      collection { get :recoveries }
    end
    # Below are admin controllers, inherit from Organized::AdminController not BaseController
    resources :manage, only: [:index, :update, :destroy] do
      collection do
        get :dev
        get :locations
      end
    end
    resources :users, except: [:show]
    resources :emails
  end

  get '*unmatched_route', to: 'errors#not_found' if Rails.env.production? # Handle 404s with lograge
end

app/controllers/admin/graphs_controller.rb
class Admin::GraphsController < Admin::BaseController
  def index
    redirect_to tables_admin_graphs_path if params[:tables]
  end

  def tables
  end

  def users
    render json: User.group_by_month(:created_at).count
  end

  def bikes
    bikes = Bike.unscoped
    case params[:start_at]
    when 'past_year'
      range = 1.year.ago.midnight..Time.now
    else
      range ||= bike_index_start..Time.now
    end
    bgraph = [
      { name: 'Registrations', data: bikes.group_by_month(:created_at, range: range).count },
      { name: 'Stolen', data: bikes.where(stolen: true).group_by_month(:created_at, range: range).count }
    ]
    render json: bgraph.chart_json
  end

  def show
    @graph_type = params[:id]
    range = date_range('2013-01-18 21:03:08')
    @xaxis = month_list(range).to_json
    @values1 = range_values(range, "#{params[:id]}_value").to_json
    if params[:id] == 'bikes'
      @values2 = range_values(range, "stolen_bike_value").to_json
    end
  end

  def stolen_locations
  end

  def review
    start_day = (1.week.ago - 1.day).to_date
    end_day = (1.day.ago).to_date
    xaxis = []
    days_from_this_week = (start_day..end_day).map

    days_from_this_week.each do |day|
      xaxis << day.strftime("%A")

    end
    @xaxis = xaxis.to_json
  end

  protected

  def bike_index_start
    Time.zone.parse('2007-01-01 1:00')
  end

  def date_range(start_date)
    date_from  = Date.parse(start_date)
    date_to    = Date.today
    date_range = date_from..date_to
    date_months = date_range.map {|d| Date.new(d.year, d.month, 1) }.uniq
  end

  def month_list(range)
    range.map {|d| d.strftime "%B" }
  end

  def range_values(range, type)
    values = []
    range.each do |date|
      values << self.send(type, date)
    end
    values
  end

  def bikes_value(date)
    Ownership.where(["created_at < ?", date.end_of_month.end_of_day]).count
  end

  def stolen_bike_value(date)
    Bike.where(["created_at < ?", date.end_of_month.end_of_day]).stolen.count
  end

  def users_value(date)
    User.where(["created_at < ?", date.end_of_month.end_of_day]).count
  end

  def organizations_value(date)
    Organization.where(["created_at < ?", date.end_of_month.end_of_day]).count
  end
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  def index

  end

  def show
    @graph_type = params[:id]
    range = date_range("2013-01-18 21:03:08")
    @xaxis = month_list(range).to_json
    @values1 = range_values(range, "ownership_value").to_json
    @values2 = range_values(range, "stolen_bike_value").to_json
    # @values1 = range_values(range, "user_value").to_json
    # @values2 = range_values(range, "organization_value").to_json
    render :layout => 'graphs'
  end

protected

  def date_range(start_date)
    date_from  = Date.parse(start_date)
    date_to    = Date.today
    date_range = date_from..date_to
    date_months = date_range.map {|d| Date.new(d.year, d.month, 1) }.uniq
  end

  def month_list(range)
    range.map {|d| d.strftime "%B" }
  end

  def range_values(range, type)
    values = []
    range.each do |date|
      values << self.send(type, date)
    end
    values
  end

  def ownership_value(date)
    Ownership.where(["created_at < ?", date.end_of_month.end_of_day]).count
  end

  def stolen_bike_value(date)
    Bike.where(["created_at < ?", date.end_of_month.end_of_day]).stolen.count
  end

  def user_value(date)
    User.where(["created_at < ?", date.end_of_month.end_of_day]).count
  end

  def organization_value(date)
    Organization.where(["created_at < ?", date.end_of_month.end_of_day]).count
  end

end

app/views/admin/graphs/index.html.haml
= javascript_include_tag "//www.google.com/jsapi", "chartkick" 

%section.padded
  %h1
    Bike Index graphs
    %small
      = link_to 'View tables', tables_admin_graphs_path

%section
  %h2 Users past week
  = line_chart User.group_by_day(:created_at, range: 1.weeks.ago.midnight..Time.now).count

%section
  %h2
    Users since start
  = line_chart users_admin_graphs_path

%section
  %h2
    Bikes past year
  = line_chart bikes_admin_graphs_path(start_at: 'past_year')

%section
  %h2
    Bikes since start

  = line_chart bikes_admin_graphs_path

app/views/admin/graphs/review.html.haml
%header.with-subtitle
  %h1
    Week in review
  %p
    = link_to "Back to all graphs", admin_graphs_url

#graph-holder
  %p
    = @xaxis
  %p
    @bikes -> should be an array of ownerships created on each day of @xaxis
  %p
    @stolen_bikes -> should be an array of stolen_records created on each day of the @xaxis
  / %canvas#review-graph{ width: "1160", height: "500", data: { labels: @xaxis, values1: @values1, values2: @values2 } }
  %p
    Set the variables on the data attributes of #review-graph, then grab them in app/assets/javascripts/views/admin/admin_chart_show.js.coffee and make a chart

app/views/admin/graphs/show.html.haml
%header.with-subtitle
  %h1
    #{@graph_type.titleize} growth
  %p
    = link_to "Back to all graphs", admin_graphs_url

#graph-holder
  %canvas#graphy{ width: "1160", height: "500", data: { labels: @xaxis, values1: @values1, values2: @values2 } }

app/views/admin/graphs/stolen_locations.html.haml
= javascript_include_tag "//www.google.com/jsapi", "chartkick" 

%section
  %h1
    Stolen location graphs

#graph-holder
  %h2
    Stolen countries past year

  - countries = StolenRecord.unscoped.where("created_at >= ?", Time.zone.now.beginning_of_year).where('country_id IS NOT NULL').group(:country).count
  - groups = {}
  - countries.keys.each { |c| groups[c.name] = countries[c] if c.present? }


  = geo_chart groups

  %ul.graphs-list-values
    - groups.sort_by {|k,v| v}.reverse.each do |location|
      %li
        #{location[0]}: #{location[1]}

    
%section
  %h2
    Stolen states past year
  - us = Country.fuzzy_iso_find('us').id
  - states = StolenRecord.unscoped.where("created_at >= ?", 1.years.ago).where(country_id: us).where('state_id IS NOT NULL').group(:state).count
  - display = ''
  - states.keys.each { |state| display += ",['#{state.name}', #{states[state]}]" }

  #stolen_month_us

  / %ul.graphs-list-values
  /   - states.sort_by {|k,v| v}.reverse.each do |location|
  /     %li
  /       #{location[0]}: #{location[1]}
  :javascript
    google.load('visualization', '1', {'packages': ['geochart']});
    google.setOnLoadCallback(drawMarkersMap);
    function drawMarkersMap() {
      var data = google.visualization.arrayToDataTable([
        ['State',  'Thefts']#{display}
      ]);

      var options = {
        region: 'US',
        resolution: 'provinces',
        displayMode: 'markers',
        colorAxis: {colors: ['#3498DB', '#2C3E50']}
      };

      var chart = new google.visualization.GeoChart(document.getElementById('stolen_month_us'));
      chart.draw(data, options);
    };

app/views/admin/graphs/tables.html.haml
%section
  %h1
    Bike Index records tables
    %small
      = link_to 'View graphs', admin_graphs_path
.special-search-field-container
  .special-search-field
    = form_tag tables_admin_graphs_path, method: :get do
      = text_field_tag :location, params[:location], placeholder: 'Location'
      = text_field_tag :location_radius, params[:location_radius], placeholder: 'Proximity in miles'
      = hidden_field_tag :tables, true
      = submit_tag 'Load', name: 'search', class: 'button-blue'
- years = Array(2013..Time.now.year)
- dates = years.map { |y| Date.civil(y, 6, 6) }
- yday = Time.zone.now.yday
- days_left = Time.zone.now.end_of_year.yday - yday

%h2
  Records everywhere
%p
  The
  %span.less-strong
    data in this color
  is (simplified, not accounting for seasonalness) projections for the end of the current year

%table.table.table-striped.table-bordered
  %thead
    %th
    %th Stolen in year
    %th Total stolen by eoy
    %th Recovered in year
    %th Stolen & non, in year
    %th Total Stolen & non by eoy
    %th Users in year
  %tbody
    - years.each_with_index do |year, index|
      / - cache("admin_table_count_#{year}", expires_in: 1.hour) do
      - date = dates[index]
      %tr
        %td
          = year
        %td
          / Because of data import from SBR - after, we want created_at,it's more reliable
          / because we automatically take it, also, people reporting previous thefts, etc
          - if [2013, 2014].include?(year)
            = StolenRecord.unscoped.where(date_stolen: date.all_year).count
          - else
            = count = StolenRecord.unscoped.where(created_at: date.all_year).count
            - if year == Time.zone.now.year
              %span.less-strong
                = s_project = count + (BigDecimal.new(count) / yday * days_left).to_i
        %td
          = count = StolenRecord.unscoped.where('created_at < ?', date.end_of_year).count
          - if year == Time.zone.now.year
            %span.less-strong
              = s_project + count
        %td
          = count = StolenRecord.unscoped.where(date_recovered: date.all_year).count
          - if year == Time.zone.now.year
            %span.less-strong
              = count + (BigDecimal.new(count) / yday * days_left).to_i
        %td
          = count = Bike.unscoped.where(created_at: date.all_year).count
          - if year == Time.zone.now.year
            %span.less-strong
              = a_project = count + (BigDecimal.new(count) / yday * days_left).to_i
        %td
          = count = Bike.unscoped.where('created_at < ?', date.all_year.last).count
          - if year == Time.zone.now.year
            %span.less-strong
              = a_project + count
        %td
          = count = User.unscoped.where(created_at: date.all_year).count
          - if year == Time.zone.now.year
            %span.less-strong
              = count + (BigDecimal.new(count) / yday * days_left).to_i
.padded
.padded
- location_radius = params[:location_radius].present? ? params[:location_radius].to_i : 100
- box = params[:location].present? && Geocoder::Calculations.bounding_box(params[:location], location_radius)
- if box && !box[0].nan?
  %h2.padded
    Records in
    %strong
      = params[:location]
    %small
      within #{location_radius} miles
  %table.table.table-striped.table-bordered
    %thead
      %th
      %th Stolen in year
      %th Total stolen by eoy
      %th Recovered in year
      %th Stolen & non, in year
      %th Total Stolen & non by eoy
      %th Users in year
    %tbody
      - years.each_with_index do |year, index|
        - date = dates[index]
        %tr
          %td
            = year
          %td
            / Because of data import from SBR - after, we want created_at,it's more reliable
            / because we automatically take it, also, people reporting previous thefts, etc
            - if [2013, 2014].include?(year)
              = StolenRecord.unscoped.where(date_stolen: date.all_year).within_bounding_box(box).count
            - else
              = count = StolenRecord.unscoped.where(created_at: date.all_year).within_bounding_box(box).count
              - if year == Time.zone.now.year
                %span.less-strong
                  = s_project = count + (BigDecimal.new(count) / yday * days_left).to_i
          %td
            / To calculate for a specific time period:
            / StolenRecord.unscoped.where(created_at: Time.now.beginning_of_month..Time.now).within_bounding_box(Geocoder::Calculations.bounding_box('Seattle', 25)).count
            = count = StolenRecord.unscoped.where('created_at < ?', date.end_of_year).within_bounding_box(box).count
            - if year == Time.zone.now.year
              %span.less-strong
                = s_project + count
          %td
            = count = StolenRecord.unscoped.where(date_recovered: date.all_year).within_bounding_box(box).count
            - if year == Time.zone.now.year
              %span.less-strong
                = count + (BigDecimal.new(count) / yday * days_left).to_i
          %td
          %td
          %td

- else
  %h2
    %em
      Add a location to the search section at the top of the page to see stats about that location
  - if params[:location].present?
    %h4
      The location and proximity you entered weren't useable. Try again.