config/routes.rb
require 'soulheart/server'
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
Bikeindex::Application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth/applications'
    controllers authorizations: 'oauth/authorizations'
    controllers authorized_applications: 'oauth/authorized_applications'
  end

  get '/shop', to: redirect('https://bikeindex.myshopify.com'), as: :shop
  get '/store', to: redirect('https://bikeindex.myshopify.com'), as: :store
  get '/discuss', to: redirect('https://discuss.bikeindex.org'), as: :discuss
  get 'discourse_authentication', to: 'discourse_authentication#index'

  resources :organizations do
    member do
      get :embed
      get :embed_extended
      get :embed_create_success
    end
  end

  get '/', to: redirect(:root_url, subdomain: false), constraints: { subdomain: 'stolen' }
  root to: 'welcome#index'

  LandingPages::ORGANIZATIONS.each do |slug|
    get slug, to: 'landing_pages#show', organization_id: slug
  end

  %w(for_shops for_advocacy for_law_enforcement for_schools new_homepage).freeze.each do |page|
    get page, controller: 'landing_pages', action: page
  end

  %w(update_browser user_home choose_registration goodbye bike_creation_graph).freeze.each do |page|
    get page, controller: 'welcome', action: page
  end

  get 'update_browser', to: 'welcome#update_browser'
  get 'user_home', to: 'welcome#user_home'
  get 'choose_registration', to: 'welcome#choose_registration'
  get 'goodbye', to: 'welcome#goodbye'
  get 'bike_creation_graph', to: 'welcome#bike_creation_graph'

  resource :session, only: [:new, :create, :destroy]
  get 'logout', to: 'sessions#destroy'

  resources :payments
  resources :documentation, only: [:index] do
    collection do
      get :api_v1
      get :api_v2
      get :api_v3
      get :o2c
      get :authorize
    end
  end

  resources :ownerships, only: [:show]
  resources :memberships, only: [:update, :destroy]

  resources :stolen_notifications, only: [:create, :new]

  resources :feedbacks, only: [:index, :create]
  get 'vendor_signup', to: redirect('/organizations/new')
  get 'connect_lightspeed', to: 'organizations#connect_lightspeed'
  get 'help', to: 'feedbacks#index'
  get 'feedbacks/new', to: redirect('/help')
  %w(support contact contact_us).each { |p| get p, to: redirect('/help') }

  resources :users, only: [:new, :create, :show, :edit, :update] do
    collection do
      get 'confirm'
      get 'request_password_reset'
      post 'password_reset'
      get 'password_reset'
      get 'update_password'
    end
  end
  get :my_account, to: 'users#edit', as: :my_account
  get :accept_vendor_terms, to: 'users#accept_vendor_terms'
  get :accept_terms, to: 'users#accept_terms'
  resources :user_embeds, only: [:show]
  resources :user_emails, only: [:destroy] do
    member do
      post 'resend_confirmation'
      get 'confirm'
      post 'make_primary'
    end
  end
  resources :news, only: [:show, :index]
  resources :blogs, only: [:show, :index]
  get 'blog', to: redirect('/news')

  resources :public_images, only: [:create, :show, :edit, :update, :destroy] do
    collection do
      post :order
    end
    member { post :is_private }
  end

  resources :registrations, only: [:new, :create] do
    collection { get :embed }
  end

  resources :bikes do
    collection { get :scanned }
    member do
      get :spokecard
      get :scanned
      get :pdf
    end
    resource :recovery, only: [:edit, :update], controller: 'bikes/recovery'
  end

  resources :locks, except: [:show, :index]

  namespace :admin do
    root to: 'dashboard#index'
    resources :bikes do
      collection do
        get :duplicates
        put :ignore_duplicate_toggle
        get :missing_manufacturer
        post :update_manufacturers
        put :unrecover
      end
      member { get :get_destroy }
    end
    get 'invitations', to: 'dashboard#invitations'
    get 'maintenance', to: 'dashboard#maintenance'
    put 'update_tsv_blacklist', to: 'dashboard#update_tsv_blacklist'
    get 'tsvs', to: 'dashboard#tsvs'
    get 'bust_z_cache', to: 'dashboard#bust_z_cache'
    get 'destroy_example_bikes', to: 'dashboard#destroy_example_bikes'
    resources :memberships, :organization_invitations,
              :paints, :ads, :recovery_displays, :mail_snippets
    resources :organizations do
      resources :custom_layouts, only: [:index, :edit, :update], controller: 'organizations/custom_layouts'
    end
    get 'recover_organization', to: 'organizations#recover'
    get 'show_deleted_organizations', to: 'organizations#show_deleted'

    resources :flavor_texts, only: [:destroy, :create]
    resources :stolen_bikes do
      member { post :approve }
    end
    resources :customer_contacts, only: [:create]
    resources :recoveries do
      collection { post :approve }
    end
    resources :stolen_notifications do
      member { get :resend }
    end
    resources :graphs, only: [:index] do
      collection do
        get :tables
        get :bikes
        get :users
        get :stolen_locations
      end
    end
    resources :failed_bikes, only: [:index, :show]
    resources :feedbacks, only: [:index, :show] do
      collection { get :graphs }
    end
    resources :ownerships, only: [:edit, :update]
    resources :tweets
    get 'blog', to: redirect('/news')
    resources :news do
      collection do
        get :listicle_image_edit
      end
    end
    resources :ctypes, only: [:new, :create, :index, :edit, :update, :destroy] do
      collection { post :import }
    end
    resources :manufacturers do
      collection { post :import }
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end

  namespace :api, defaults: { format: 'json' } do
    get '/', to: redirect('/documentation')
    namespace :v1 do
      resources :bikes, only: [:index, :show, :create] do
        collection do
          get 'search_tags'
          get 'close_serials'
          get 'stolen_ids'
        end
      end
      resources :stolen_locking_response_suggestions, only: [:index]
      resources :cycle_types, only: [:index]
      resources :wheel_sizes, only: [:index]
      resources :component_types, only: [:index]
      resources :colors, only: [:index]
      resources :handlebar_types, only: [:index]
      resources :frame_materials, only: [:index]
      resources :manufacturers, only: [:index, :show]
      resources :notifications, only: [:create]
      resources :organizations, only: [:show]
      resources :users do
        collection do
          get 'current'
          post 'request_serial_update'
          post 'send_request'
        end
      end
      get 'not_found', to: 'api_v1#not_found'
      get '*a', to: 'api_v1#not_found'
    end
    mount Soulheart::Server, at: '/autocomplete'
  end
  mount API::Base => '/api'

  resources :stolen, only: [:index, :show] do
    collection do
      get 'current_tsv'
    end
  end

  resources :manufacturers, only: [:index] do
    collection { get 'tsv' }
  end
  get 'manufacturers_tsv', to: 'manufacturers#tsv'

  resources :organization_deals, only: [:create, :new]
  resource :integrations, only: [:create]
  get '/auth/:provider/callback', to: 'integrations#create'
  get '/auth/failure', to: 'integrations#integrations_controller_creation_error'

  %w(support_the_index support_the_bike_index protect_your_bike privacy terms
     serials about where vendor_terms resources image_resources
     how_not_to_buy_stolen dev_and_design lightspeed).freeze.each do |page|
    get page, controller: 'info', action: page
  end
  get 'lightspeed_integration', to: redirect('/lightspeed')

  %w(stolen_bikes roadmap security spokecard how_it_works).freeze.each { |p| get p, to: redirect('/resources') }

  # get 'sitemap.xml.gz' => redirect('https://files.bikeindex.org/sitemaps/sitemap_index.xml.gz')
  # Somehow the redirect drops the .gz extension, which ruins it so this redirect is handled by Cloudflare
  # get 'sitemaps/(*all)' => redirect('https://files.bikeindex.org/sitemaps/%{all}')

  get '/400', to: 'errors#bad_request', via: :all
  get '/401', to: 'errors#unauthorized', via: :all
  get '/404', to: 'errors#not_found', via: :all
  get '/422', to: 'errors#unprocessable_entity', via: :all
  get '/500', to: 'errors#server_error', via: :all

  mount Sidekiq::Web => '/sidekiq', constraints: AdminRestriction

  # No actions are defined here, this `resources` declaration
  # prepends a :organization_id/ to every nested URL.
  # Down here so that it doesn't override any other routes
  resources :organizations, only: [], path: 'o', module: 'organized' do
    get '/', to: 'bikes#index', as: :root
    get 'landing', to: 'manage#landing', as: :landing
    resources :bikes, only: [:index, :new, :show] do
      collection { get :recoveries }
    end
    # Below are admin controllers, inherit from Organized::AdminController not BaseController
    resources :manage, only: [:index, :update, :destroy] do
      collection do
        get :dev
        get :locations
      end
    end
    resources :users, except: [:show]
    resources :emails
  end

  get '*unmatched_route', to: 'errors#not_found' if Rails.env.production? # Handle 404s with lograge
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  layout 'application_revised'
  # caches_page :about, :where, :roadmap, :security, :serials, :stolen_bikes, :privacy, :terms, :vendor_terms, :downloads, :resources, :spokecard

  def about
  end

  def where
    @organizations = Organization.shown_on_map
  end

  def serials
  end

  def protect_your_bike
  end

  def lightspeed
    session[:return_to] = lightspeed_url unless current_user.present?
    @organization = Organization.new
  end

  def privacy
  end

  def terms
  end

  def vendor_terms
  end

  def resources
  end

  def image_resources
  end

  def support_the_index
    @page_title = 'Support Bike Index'
    render layout: 'payments_layout'
  end

  def support_the_bike_index
    redirect_to support_the_index_url
  end

  def dev_and_design
  end

  def how_not_to_buy_stolen
    redirect_to 'https://files.bikeindex.org/stored/dont_buy_stolen.pdf'
  end
end

app/views/info/dev_and_design.html.haml
%h1
  Development and design resources
%h5
  Bike Index is meant to be useable and expandable by everyone. We're way into the open source.
%p
  Here are some other things that might be interesting or useful:
%ul
  %li
    Bike Index itself is open source - check it out #{ link_to 'on GitHub', 'https://github.com/bikeindex/bike_index' }.
  %li
    = link_to 'Our API documentation', documentation_index_path
  %li
    = link_to 'Image and design assets', image_resources_path
  %li
    #{ link_to 'Nearby stolen widget', 'https://github.com/bikeindex/stolen_bikes_widget_html' } (on GitHub)
  %li
    - url_for_embed = current_user ? user_embed_path(current_user) : new_user_url(return_to: dev_and_design_path)
    #{ link_to 'Personal bike display widget', url_for_embed } (must be logged in - also, has no usage instructions...)
  %li
    #{link_to "OAuth Applications you've made", oauth_applications_path } (must be logged in)
  %li
    #{ link_to "OAuth Applications you've authorized", oauth_authorized_applications_path } (must be logged in)

app/views/info/image_resources.html.haml
%h1
  Bike Index image assets


%ul.serial-pictures
  %li
    %a.serial-image.blackbg{ href: image_path('resources/logo_bordered.svg') }
      = image_tag('resources/logo_bordered.svg', alt: 'Basic logo')
    %p
      Logo with blue shield and white text (#{link_to 'svg', image_path('resources/logo_bordered.svg') }, #{link_to 'png', image_path('resources/logo_bordered.png') })
      %br
      %small.less-strong
        Black background shown here for visibility
  %li
    %a.serial-image{ href: image_path('resources/logo_striped.svg') }
      = image_tag('resources/logo_striped_short.svg', alt: 'Logo with stripes')
    %p
      Striped logo (#{link_to 'svg', image_path('resources/logo_striped.svg') }, #{link_to 'png', image_path('resources/logo_striped.png') })
  %li
    %a.serial-image{ href: image_path('resources/logo.svg') }
      = image_tag('resources/logo.svg', alt: 'Single color logo')
    %p
      Basic logo (#{link_to 'svg', image_path('resources/logo.svg') }, #{link_to 'png', image_path('resources/logo.png') })
  
  %li
    %a.serial-image.blackbg{ href: image_path('resources/logo_white.svg') }
      = image_tag('resources/logo_white.svg', alt: 'Single color logo in white')
    %p
      Basic logo in white (#{link_to 'svg', image_path('resources/logo_white.svg') }, #{link_to 'png', image_path('resources/logo_white.png') })
      %br
      %small.less-strong
        image has no background, shown here with black for visibility

  %li
    %a.serial-image.blackbg{ href: image_path('resources/logo_backgrounded.svg') }
      = image_tag('resources/logo_backgrounded.svg', alt: 'Logo with background cutout')
    %p
      Logo with background cutout (#{link_to 'svg', image_path('resources/logo_backgrounded.svg') }, #{link_to 'png', image_path('resources/logo_backgrounded.png') })
      %br
      %small.less-strong
        Black background shown here for visibility

app/views/info/lightspeed.html.haml
.vendor-signup
  %h1
    How to: Lightspeed Retail and Bike Index Integration
  %article
    .padded

    %p
      This page gives instructions on integrating Bike Index registration with your Lightspeed Retail POS system. <strong><a href="#{about_url}">Read our about page</a></strong> for general information about what Bike Index is and why it's important.
  %hr
  %article
    %p
      At Bike Index we believe that bicycle registration is one of the simplest and most effective ways to fight bicycle theft. By offering complete integration with Lightspeed Retail, we've made registration a quick, painless, and automated process for you and your customers.

    - if current_user.present? && current_user.memberships.present?
      %p
        All you have to do is go to #{ link_to 'bikeindex.org/connect_lightspeed', connect_lightspeed_path }, where you'll be asked to authorize Bike Index to access your Lightspeed Account.
    - else
      %p
        The first step is to create an account for yourself and your shop - you can do that <a href="#add_organization" class="scroll-to-ref">at the bottom of this page</a>
      %p
        Once you have a Bike Index account set up for your shop, there will be a link on this page to take you to the integration.

    %p
      Once your Lightspeed Retail account is connected to your Bike Index account with automatic registration turned on, a listing on Bike Index will be automatically created for every bicycle you sell. All you need to do is add the customer's email address and the bicycle's serial number during a normal Lightspeed Retail checkout.

  %article.padded
    %p
      The bicycle's owner will receive an email with all the information he or she needs to log in and maintain the account as well as a PDF copy of the registration information.
    %h3
      A few things to note:

  %ul.fancy-bullets
    %li
      %span.blue-bullet
      %p
        If a customer doesn't want a bike to be added to Bike Index, simply write "DO NOT REGISTER" in the notes for the sale and the bicycle will not be registered.
    %li
      %span.blue-bullet
      %p
        Bicycles sold before you activated Lightspeed Retail integration will not be registered.
    %li
      %span.blue-bullet
      %p
        We know you and your customers are concerned about privacy and access to your sales and customer information. Bike Index is committed to keeping your information safe and secure, and we will never send your customers unsolicited email. You can our #{link_to "Privacy Policy here", privacy_url}.
    %li
      %span.blue-bullet
      %p
        We're happy to answer any questions you have about making Bike Index work with Lightspeed Retail and we're always looking for ways to improve the integration. Please #{link_to "support@bikeindex.org", "mailto:support@bikeindex.org"} with any questions, concerns, comments, or suggestions.


    %blockquote
      I started Bike Index because I wanted to register bikes for my customers at the shop where I worked &mdash; with this integration, we're finally able to give shops a way to register bikes that doesn't interfere with selling them.
    .blockquote-cite
      \- Seth Herr, Bike Index co-founder

  / .vendor-questions.tabbable
  /   %ul.nav-tabs
  /     %li.active
  /       %a{ href: '#what_we_are', data: {toggle: 'tab'} }
  /         What Bike Index is
  /     %li
  /       %a{ href: '#how_lightspeed_integration_works', data: {toggle: 'tab'} }
  /         How the integration works
      
  /   .tab-content
  /     %span.vendor-tab-bg
  /     #what_we_are.tab-pane.active
  /       %article
  /         %p
  /           Bicycle registration is a vital part of keeping bikes safe.

  /         %p
  /           While we know not every registered bike that is stolen will be recovered, unregistered stolen bikes are almost guaranteed to never turn up again. This is why we created Bike Index – to provide fast, free, and easy registration that people would actually want to use, so we could help recover stolen bikes.
  /         %p
  /           Just about everyone wants their bikes to be registered &mdash; but most people never bother to register on their own. It makes a lot of sense to register bikes right when they are sold - which is why we've partnered with Lightspeed Retail to do just that.
  /         %p
  /           We designed Bike Index from the outset to be a great way for bike shops to register bikes for their customers. If you register a bike for a customer, we will send them an email with the basic information about their bike in case they ever need it &mdash; and that's it.
  /         %p
  /           Registrants can log into the Index and edit their bikes later on, but they're protected even if they choose not to. Furthermore, Bike Index will never trade or sell their email, or send any sort of marketing to them. We just protect their bikes, for free, because it's what we do.
  /         %p
  /           Read more about #{link_to "how and why Bike Index works", how_it_works_url}.
  /     #how_lightspeed_integration_works.tab-pane
  /       %article.padded
  /         %p
  /           Once you connect your Lightspeed account, we will register every bike you sell automatically (unless you write "Do not sell" in the sales note). If you'd prefer, you can make the integration wait for approval before registering the bikes though.
  /         %p
  /           We're an #{link_to "official integration with Lightspeed Retail", "http://www.lightspeedpos.com/retail/addons/", target: '_blank'} - you can find us in their
  /           %em
  /             Great tools for bicycle retailers
  /           section. We've been vetted and approved by Lightspeed &mdash; we protect your data and we'll help protect your customers' bikes.

  /         %p
  /           Setting up the integration is easy:
  /         %ol
  /           - unless current_user.present? && current_user.memberships.present?
  /             %li
  /               %p
  /                 Add your organization to Bike Index (<a href="#add_organization" class="scroll-to-ref">below</a>)
  /           %li
  /             %p
  /               - if current_user.present? && current_user.memberships.count > 0
  /                 - org = current_user.organizations.first
  /                 Go to the
  /                 %a{ href: "https://pos_integration.bikeindex.org/organizations/connect?id=#{org.slug}&access_token=#{org.access_token}"}
  /                   Lightspeed Retail Integration
  /               - else
  /                 Click on the Lightspeed Retail Integration button (at the bottom of the page for your organization once you've signed up).
                  
  /           %li
  /             %p
  /               Click on "integrate with Bike Index" and follow the steps with Lightspeed Retail to connect your account.
          
  /         %p.padded
  /           And that's it. Every bike you sell will be registered, so long as you put in the customer's email and the bike has a serial number in the "serial number" field in Lightspeed.
  /         %p
  /           If a customer doesn't want to be registered, put "do not register" in the notes for the sale and we won't register the bike.
          
  /         .alert.alert-info
  /           %p
  /             We will not automatically register bikes that were sold before you signed up for the integration.
  /           %p
  /             You can register these bikes manually or #{link_to "contact us", "mailto:seth@bikeindex.org"} for assistance.
  /           /   You can register these bikes by clicking edit, checking the "register despite issues" checkbox, and clicking the "Update bike" button. If you'd like to register a large quantity, #{link_to "contact us", "mailto:seth@bikeindex.org"}.

  %hr

  %article.padded.vendor-signup-form.bottom-padded#add_organization
    %h3
      Sign your shop up


    = render "/organizations/new_form"

app/views/info/privacy.html.erb
<% file_path = @view_renderer.lookup_context.find_template(@virtual_path).identifier.gsub(/\A.*\/app\//i, 'app/') %>
<div id="legal-terms" class="inner-recep legal-content">
  <header>
  <h1>
    <a name="privacy-policy" class="anchor" href="#privacy-policy"><span class="mini-icon mini-icon-link"></span></a>
    Privacy Policy
  </h1>
  <p>Last updated July 29th, 2017. Previous versions and the change history is <a href="https://github.com/bikeindex/bike_index/tree/master/<%= file_path %>">available here</a>.</p>

  <hr>
  </header>

  <h2>
    <a name="privacy-general-information" class="anchor" href="#privacy-general-information"><span class="mini-icon mini-icon-link"></span></a>
    General Information
  </h2>
  
  <p>Please see the <%= link_to 'Terms of Service', terms_path %> for definitions of terms.</p>
  
  <p>We collect the e-mail addresses and other shared personal information of those who communicate with us, aggregate information on the pages Users access or visit and the functions Users perform on pages, and information volunteered by Users (such as survey information and/or site registrations). The information we collect is used to improve the content of our Web pages and the quality of our Service, and is not shared with or sold to other organizations for commercial purposes, except to provide products or services you've requested, when we have your permission, or under the following circumstances:</p>

  <p>It is necessary to share information in order to investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations of Terms of Service of the specific application, or as otherwise required by law.</p>

  <p>We transfer information about you if Bike Index is acquired by or merged with another company. In this unlikely event, Bike Index will notify you via e-mail before information about you is transferred and becomes subject to a different privacy policy.</p>

  <h2>
    <a name="privacy-information-gathering-and-usage" class="anchor" href="#information-gathering-and-usage"><span class="mini-icon mini-icon-link"></span></a>
    Information Gathering and Usage
  </h2>

  <p>When you register for Bike Index we may ask for information such as your name, email address, billing address, or phone number. The only required field is e-mail. Whatever you choose to share, You can either show or hide from the public on your Bike Index Account.</p>

  <p>Bike Index uses collected information for the following general purposes: provision of products and services, identification and authentication, services improvement, contact, and research.</p>

  <h2>
    <a name="cookies" class="anchor" href="#cookies"><span class="mini-icon mini-icon-link"></span></a>
    Cookies
  </h2>

  <p>A cookie is a small amount of data, which often includes an anonymous unique identifier, that is sent to your browser from a web site's computers and is stored on your computer's hard drive. The stored information helps you connect more quickly to sites you’ve previously visited.</p>

  <p>Cookies are required to use Bike Index Service.</p>

  <p>We use cookies to record current session information, but do not use permanent cookies. For example, you are required to re-login to your Bike Index account after a certain period of time has elapsed to protect you against others accidentally or intentionally accessing your Account contents.</p>


  <h2>
    <a name="data-storage" class="anchor" href="#data-storage"><span class="mini-icon mini-icon-link"></span></a>
    Data Storage
  </h2>

  <p>Bike Index uses third party vendors and hosting partners to provide the necessary hardware, software, networking, storage, and related technology required to run Bike Index. Although Bike Index does own the code, databases, and all rights to Bike Index application, you retain all rights to your data.</p>

  <h2>
    <a name="disclosure" class="anchor" href="#disclosure"><span class="mini-icon mini-icon-link"></span></a>
    Disclosure
  </h2>

  <p>
    Bike Index may disclose personally identifiable information under special circumstances, such as to comply with subpoenas or when your actions violate the <a href="https://bikeindex.org/terms">Terms of Service</a>.
  </p>

  <h2>
    <a name="changes" class="anchor" href="#changes"><span class="mini-icon mini-icon-link"></span></a>
    Changes
  </h2>

  <p>Bike Index may periodically update this policy. We will notify you about significant changes by sending a notice to the primary email address specified in your Bike Index Service Account or by placing a prominent notice on our site. Such notices shall be considered to be received by you within 24 hours of the time it is posted to our website or emailed to you unless we receive notice that the email was not delivered.</p>

  <p>You retain the right to access, amend, correct or delete your personal information where it is inaccurate at any time. To do so, please contact <a href="mailto:contact@bikeindex.org">contact@bikeindex.org</a>.</p> 


  <h2>
    <a name="questions" class="anchor" href="#questions"><span class="mini-icon mini-icon-link"></span></a>
    Questions
  </h2>

  <p>Any questions about this Privacy Policy should be addressed to <a href="mailto:contact@bikeindex.org">contact@bikeindex.org</a></p>
</div>

app/views/info/resources.html.haml
%h1
  Bike Index Resources

%ul
  %li
    %p
      <strong>Infographic</strong>:
      %a{ href: how_not_to_buy_stolen_url }
        How not to buy a stolen bike in 4 easy steps
  %li
    %p
      Check out our #{link_to "map of bike thefts", "http://map.bikewise.org"}.
  %li
    %p
      Get Bike Index #{link_to "logos and design assets", image_resources_url}.
  %li
    %p
      Did you know every bike has a unique, identifying number? #{link_to "Learn about serial numbers here", serials_url}.
  %li
    %p
      View the list of all
      = link_to "the manufacturers", manufacturers_url
      we know about.
  %li
    %p
      We're open source, view this app (and other things) on #{link_to "GitHub", "https://github.com/bikeindex", target: "_blank"}.
  %li
    %p
      We have an open API - check out our #{link_to "API documentation", documentation_index_url}.

= render '/shared/content_footer_ad'

app/views/info/serials.html.haml
%h1
  Serial numbers
%p#fnref-all-bikes-serials
  All bikes 
  %sup
    %a.footnote-ref{ href: '#fn-all-bikes-serials' }
      1
  all have unique serial numbers.

%p
  Most bicycles have their serial number engraved beneath their bottom bracket, but sometimes serial numbers are found in other places. Here are some examples of where and what to look for:


%ul.serial-pictures
  %li
    = link_to image_tag('serials/serial_bb.jpg', alt: 'Bike with bottom bracket circled'), image_path('serials/serial_bb.jpg'), class: 'serial-image'
    %p
      The bottom bracket (where serial numbers are typically located) is circled.
  %li
    = link_to image_tag('serials/serial_peters.jpg', alt: 'Standard serial number'), image_path('serials/serial_peters.jpg'), class: 'serial-image'
    %p
      A serial number on the underside of a bottom bracket.
  %li
    = link_to image_tag('serials/serial_fixie.jpg', alt: 'Another standard serial number. Sometime to be replaced with a serial number covered up by routing.'), image_path('serials/serial_fixie.jpg'), class: 'serial-image'
    %p
      Another serial number beneath the bottom bracket, aligned parallel to the frame.
  %li
    = link_to image_tag('serials/serial_headtube.jpg', alt: 'Schwinn Serial.'), image_path('serials/serial_headtube.jpg'), class: 'serial-image'
    %p
      Some Schwinn bicycles have the unique identifying number on their head tube (which is on the front of the bike).
  
  %li
    = link_to image_tag('serials/serial_pinsch.jpg', alt: 'Doberman dropout serial number'), image_path('serials/serial_pinsch.jpg'), class: 'serial-image'
    %p
      A serial number located on a rear drop out. Some BMX bikes and a few Schwinn bicycles place the serial on the rear dropout.  On older Schwinns there are numbers stamped on both the drive side and non-drive side rear dropouts; the one on the non-drive side dropout is the serial number.


  %li#fnref-all-bikes-serials
    = link_to image_tag('serials/serial_look.jpg', alt: 'Look serial number'), image_path('serials/serial_look.jpg'), class: 'serial-image'
    %p
      Some bikes have multiple serial numbers.
      %sup
        %a.footnote-ref{ href: '#fn-second-serial-number' }
          2
      When adding a bike to the Index, it's best to enter all the groups of numbers and letters separated by spaces.

%p
  Hopefully you can find the serial number on the bicycle you're looking at,
  / # = link_to 'Check out the forum', discuss_url
  email #{link_to 'contact@bikeindex.org', 'mailto:contact@bikeindex.org'}
  if you're having trouble.

= render '/shared/content_footer_ad'

.footnotes
  %ol
    %li#fn-all-bikes-serials
      Okay, fine, so 
      %em
        maybe
      there are a few bikes without serial numbers, but this is rare and typical only on hand made bikes or really old bicycles.
      %a.footnote-back-link{ href: "#fnref-all-bikes-serials", title: "Jump back to footnote 1 in the text."}
        &#8617;
    %li#fn-second-serial-number
      In this picture
      %em
        200910427-2A
      is a manufacturer number and not a serial number. However, to make bikes as easy as possible to find, we'd love it if you entered all numbers you encounter.
      %a.footnote-back-link{ href: "#fnref-second-serial-number", title: "Jump back to footnote 2 in the text."}
        &#8617;    

app/views/info/support_the_index.html.haml
= render '/payments/form'

app/views/info/terms.html.haml
.inner-recep.legal-content#legal-terms
  = render partial: "/info/terms_text"

app/views/info/vendor_terms.html.haml
.inner-recep.legal-content#legal-terms
  = render partial: "/info/vendor_terms_text"